name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:       
  build:
    name: Builds the Docker image with downloaded coco image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | #!/bin/bash
             cd ./docker/opt/app/model
             rm saved_model.pb
             wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
             tar -xvf ssd_mobilenet_v1_coco_2018_01_28.tar.gz ssd_mobilenet_v1_coco_2018_01_28/saved_model/saved_model.pb       
             docker image build ./docker --tag my-image-name:$(date +%s)
          
